name: path_positions
frame_id: world_frame
num_points: 9

points:
  - [-1.5,  1.5,  0.0]
  - [-1.5, -1.5,  0.0]
  - [ 1.5,  1.5,  0.0]
  - [ 1.5, -1.5,  0.0]
  - [-1.5,  1.5,  0.0]
  - [ 1.5,  1.5,  0.0]
  - [ 2.0,  0.0,  0.0]
  - [ 1.5, -1.5,  0.0]
  - [-1.5, -1.5,  0.0]